DefaultContentLanguage = "hu"
baseURL = ""
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = true
theme = "Intellident"
title = "Intellident"
[languages.en]
languageName = "English"
weight = 2
[[languages.en.menu.main]]
name = "Home"
pre = "fa fa-home"
url = "/en/"
weight = 1
[[languages.en.menu.main]]
identifier = "treatments"
name = "Treatments"
pre = "fa fa-user-md"
url = "/en/treatments"
weight = 2
[[languages.en.menu.main]]
name = "Prices"
pre = "fa fa-list-ul"
url = "/en/pages/prices/"
weight = 3
[[languages.en.menu.main]]
identifier = "team"
name = "Our Team"
pre = "fa fa-users"
url = "/en/team"
weight = 4
[[languages.en.menu.main]]
name = "About Us"
pre = "fa fa-align-center"
url = "/en/pages/about/"
weight = 5
[[languages.en.menu.main]]
name = "CBCT"
pre = "fa fa-camera"
url = "/en/pages/cbct/"
weight = 6
[[languages.en.menu.main]]
name = "Contact"
pre = "fa fa-address-book"
url = "/en/#contact"
weight = 7
[languages.en.params]
description = "Intellident dental office. The key to the success of our treatments is proper oral care!"
[languages.hu]
contentDir = "content/"
languageName = "Magyar"
weight = 1
[[languages.hu.menu.main]]
name = "Főoldal"
pre = "fa fa-home"
url = "/"
weight = 1
[[languages.hu.menu.main]]
identifier = "treatments"
name = "Kezelések"
pre = "fa fa-user-md"
url = "/treatments"
weight = 2
[[languages.hu.menu.main]]
name = "Áraink"
pre = "fa fa-list-ul"
url = "/pages/prices/"
weight = 3
[[languages.hu.menu.main]]
identifier = "team"
name = "Csapatunk"
pre = "fa fa-users"
url = "/team"
weight = 4
[[languages.hu.menu.main]]
name = "Rólunk"
pre = "fa fa-align-center"
url = "/pages/about"
weight = 5
[[languages.hu.menu.main]]
name = "CBCT"
pre = "fa fa-camera"
url = "/pages/cbct/"
weight = 6
[[languages.hu.menu.main]]
name = "Kapcsolat"
pre = "fa fa-address-book"
url = "/#contact"
weight = 7
[languages.hu.params]
description = "Intellident fogorvosi rendelő. Kezeléseink sikerének alapja a helyes szájápolás!"
[params]
ogimage = "images/og-image.png"
sitename = "intellident.com"
[taxonomies]
price = "prices"
type = "types"
