---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: Magyar
- type: document
  path: content/_index.md
  label: Főoldal
- type: document
  path: content/contact.md
  label: Kapcsolat
- type: directory
  path: content/treatments
  label: Kezelések
  create: documents
  match: "**/*.hu.md"
  exclude: _index.hu.md
  new_doc_ext: hu.md
  templates:
  - treatments-template
- type: directory
  path: content/team
  label: Csapatunk
  create: documents
  match: "**/*.hu.md"
  exclude: _index.hu.md
  new_doc_ext: hu.md
  templates:
  - team
- type: document
  path: content/pages/prices.md
  label: Áraink
- type: document
  path: content/pages/about.md
  label: Rólunk
- type: document
  path: content/pages/cbct.md
  label: CBCT
- type: heading
  label: Angol
- type: document
  path: content/_index.en.md
  label: Főoldal
- type: document
  path: content/contact.en.md
  label: Kapcsolat
- type: directory
  path: content/treatments
  label: Kezelések
  create: documents
  match: "**/*.en.md"
  exclude: _index.en.md
  new_doc_ext: en.md
  templates:
  - treatments-template
- type: directory
  path: content/team
  label: Csapatunk
  create: documents
  match: "**/*.en.md"
  exclude: _index.en.md
  new_doc_ext: en.md
  templates:
  - team
- type: document
  path: content/pages/prices.en.md
  label: Áraink
- type: document
  path: content/pages/about.en.md
  label: Rólunk
- type: document
  path: content/pages/cbct.en.md
  label: CBCT
- type: heading
  label: Beállítások
- type: document
  path: content/theme-settings.md
  label: Megjelenés
- type: document
  path: content/pages/thank-you.md
  label: Űrlap üzenet
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
