---
label: Theme Settings
hide_body: true
fields:
- name: theme
  type: select
  default: Theme 1
  config:
    required: true
    options:
    - Theme 1
    - Theme 2
    - Theme 3
    - Theme 4
    - Theme 5
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Színséma
  description: 5 fajta választható színséma.
- name: banner
  type: file
  config:
    maxSize: 2
  label: Alcímek háttere
  description: Az egyes oldalakon megjelenő címek mögötti háttér.
  default: "/uploads/images/pattern/bg_100.png"
pages:
- content/theme-settings.md
